steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/snappy-mission-458211-g2/WebApi_GCP', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/snappy-mission-458211-g2/WebApi_GCP']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'WebApi_GCP',
        '--image', 'gcr.io/snappy-mission-458211-g2/WebApi_GCP',
        '--region', 'asia-south1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/snappy-mission-458211-g2/WebApi_GCP'
